name: Verify Python Submission

on:
  pull_request:
    paths:
      - 'submissions/**/verify.py'
      - 'submissions/**/*.py'

jobs:
  test-python:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pylint numpy

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39
        with:
          files: 'submissions/**/*.py'

      - name: Run pylint (Style Check)
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "Linting $file"
            pylint "$file" --disable=C0114,C0115,C0116,R0801 --max-line-length=120 || echo "Warnings found"
          done

      - name: Run Python scripts
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "Testing $file"
            python "$file" || echo "Script execution check complete"
          done

      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ Python verification checks completed! Organizer review required.'
            })